"""Design-package assembler — one markdown document from suite outputs.

Collects CalcResult reports (voltage drop, motor branch, SCCR, thermal ...),
the panel pipeline outputs (I/O summary, BOM, wire schedule, nameplate), and
free-form sections into a single design document with a table of contents.
Markdown is the neutral interchange — convert to DOCX/PDF with your preferred
toolchain.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from cst.common.cite import CalcResult
from cst.panel.bom import generate_bom
from cst.panel.io_list import IOList
from cst.panel.nameplates import PanelNameplate
from cst.panel.wire_schedule import generate_wire_schedule


def _slug(title: str) -> str:
    return "".join(c if c.isalnum() else "-" for c in title.lower()).strip("-")


def _md_table(rows: list[dict], columns: list[str]) -> str:
    lines = ["| " + " | ".join(columns) + " |",
             "|" + "|".join("---" for _ in columns) + "|"]
    lines += ["| " + " | ".join(str(r.get(c, "")) for c in columns) + " |" for r in rows]
    return "\n".join(lines)


@dataclass
class DesignPackage:
    """Accumulates sections, renders one markdown document."""

    project: str
    panel_id: str = ""
    revision: str = "A"
    prepared_by: str = ""
    sections: list[tuple[str, str]] = field(default_factory=list)

    def add_section(self, title: str, body_markdown: str) -> None:
        self.sections.append((title, body_markdown))

    def add_calc(self, result: CalcResult, title: str | None = None) -> None:
        """Attach a calculator result as a fenced, citation-bearing block."""
        self.add_section(
            title or result.name,
            f"```text\n{result.report()}\n```",
        )

    def add_io_summary(self, io_list: IOList) -> None:
        # A design package is a deliverable: refuse to assemble one from an I/O
        # list that fails validation rather than emitting tables from bad data.
        io_list.raise_for_problems()
        counts = io_list.counts_by_type()
        rows = [{"I/O type": t, "points": n} for t, n in counts.items()]
        rows.append({"I/O type": "TOTAL", "points": sum(counts.values())})
        body = _md_table(rows, ["I/O type", "points"]) + "\n\nValidation: clean."
        self.add_section("I/O Summary", body)

    def add_bom(self, io_list: IOList, **bom_kwargs) -> None:
        lines = generate_bom(io_list, **bom_kwargs)
        self.add_section(
            "Bill of Materials (structural)",
            _md_table(lines, ["item", "description", "qty", "part_number", "basis"])
            + "\n\nPart numbers to be completed from the project's approved vendor list.",
        )

    def add_wire_schedule(self, io_list: IOList, limit: int | None = 20) -> None:
        rows = generate_wire_schedule(io_list)
        shown = rows if limit is None else rows[:limit]
        body = _md_table(shown, ["wire_no", "from", "to", "terminal", "function", "color"])
        if limit is not None and len(rows) > limit:
            body += f"\n\n({len(rows) - limit} more rows — full schedule issued as CSV.)"
        self.add_section("Wire / Terminal Schedule", body)

    def add_nameplate(self, plate: PanelNameplate) -> None:
        self.add_section("Panel Nameplate Content", f"```text\n{plate.render()}\n```")

    def render(self) -> str:
        header = [
            f"# Design Package — {self.project}",
            "",
            f"| Panel | {self.panel_id or '—'} | Revision | {self.revision} |",
            "|---|---|---|---|",
            f"| Prepared by | {self.prepared_by or '—'} | Sections | {len(self.sections)} |",
            "",
            "## Contents",
            "",
        ]
        header += [
            f"{i}. [{title}](#{_slug(title)})"
            for i, (title, _) in enumerate(self.sections, start=1)
        ]
        parts = ["\n".join(header)]
        parts += [f"\n## {title}\n\n{body}\n" for title, body in self.sections]
        parts.append(
            "\n---\n*Generated by the cst toolkit. Every calculation section "
            "carries its standard citations and assumptions; verify SAMPLE-data "
            "results against licensed table values before issue.*\n"
        )
        return "\n".join(parts)
